### ISSUE TITLE
Is there a plan to support priority gas auctions (PGA)?

### ISSUE THREAD

**Issue by deterministicdavid** [simtopia/verbs#66]
Is there a plan to support priority gas auctions (PGA)?

https://www.mev.wiki/terms-and-concepts/priority-gas-auctions

**Comment by zombie-einstein** [comment]
Yes, a couple of steps we've been considering towards this:

- At the moment we just shuffle all the transactions submitted by agents, but in principle it's easy enough to make the process by which transactions are ordered customisable (and arguably more realistic).
- The simulation assumes that all the agents are effectively submitting their transactions simultaneously (as if they are acting in parallel) and do not have a view of transactions submitted by other agents. There's maybe a couple of ways we could relax this:

  - Have a event based model where agents are treated as if they update in series, and have some method by which agents are ordered/sorted to be updated. This could be an alternate way of executing the model.
  - Have an additional stage where agents can react to the current set of submitted transactions before they are processed.

Any thoughts if there is another means of achieving this effect?

**Comment by zombie-einstein** [comment]
Going to close this issue for now, gas-priority ordering is included in the latest release (v0.4.0) will revisit if we want to look at a different process of updating the model
